
import { HomeHeader } from '@components/Header/style_componets';
import { SectionTitle } from '@styles/common';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';


const Home: NextPage = () => {
  return (
    <div className='relative'>
      <Head>
        <title>Creative House</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/house.svg' />
      </Head>
       
       <HomeHeader/>
      
    </div>
  );
};

export default Home;
